### PR TITLE
Mercury/tsl 6 initial setup

### PR DESCRIPTION
**Pull request by revilokid**
"Set up logging to be used in various different files and utilities." this shall be done when I create the testing. As this is "Foreign" to me.

### CODE REVIEW

**Comment by Peders123** [comment]
Please ensure your file names are snake case compliant. Ie. API.py -> api.py, Database.py -> database.py.

**Comment by revilokid** [comment]
> Please ensure your file names are snake case compliant. Ie. API.py -> api.py, Database.py -> database.py.

Changes have been made and will be made to the rest.

**Comment by Peders123** [comment]
For the most part this setup looks fine. The file structure will need to evolve and become more complex as we progress, but that can come in later pull requests.

The biggest issue with this PR currently, there are no edits to the Dockerfile or docker-compose. The FastAPI is currently not being built in the docker build. Please update that, as well as requirements.txt to include the FastAPI stuff. You should run the FastAPI in the entrypoint using uvicorn, there will be documentation about this everywhere so dw.

**Comment by revilokid** [comment]
yeah thought about the docker compose and i feel that it was best left to last. lets me work on the fast api faster , when i do work on it, the next pull request has the changes to requirements.txt.

**Comment by revilokid** [comment]
added the docker.

**Pull request merged**
